Feature/add detection to media server
RidgeRun/coral-gst-inference-demos pull request #4
Opened 2021-03-15 22:02 UTC by jsalas98

2021-03-16 14:51 UTC, fasm22 approved these changes

2021-03-16 21:45 UTC, fasm22 approved these changes

2021-03-18 15:48 UTC, rrcarlosrodriguez requested changes

2021-03-18 15:48 UTC, rrcarlosrodriguez commented on media-server/config.txt
> -MODEL_LOCATION=/home/coral/mobilenet_v2_1.0_224_quant_edgetpu.tflite # Use absolute path.
What if we create 2 config files? one call `config_classifier.txt` and other `config_detector.txt` ? So the user don't have to mess modifying the config files and can test both easily

2021-03-18 15:48 UTC, rrcarlosrodriguez commented on media-server/media_server.sh
> +    fi
You need to reset need_save_recording to no here

2021-03-18 17:21 UTC, rrcarlosrodriguez approved these changes

2021-03-23 20:50 UTC, merged