Feature/add dectection intelligent video recording
RidgeRun/coral-gst-inference-demos pull request #6
Opened 2021-03-23 16:27 UTC by fasm22

* Replaces complex pipeline with inferencebin element
* Adds support for detection on intelligent-video-recording demo
* Adds configuration files for detection or classification

2021-03-23 19:24 UTC, rrcarlosrodriguez requested changes

2021-03-23 19:24 UTC, rrcarlosrodriguez commented on intelligent-video-recording/config_detection.cfg
> +CLASSES_ID = [74]
I think we should explain better what these numbers are in the README file. We should assume that people don't know that a number corresponds to a label and corresponds to the kind of object we will be tracking

2021-03-23 19:24 UTC, rrcarlosrodriguez commented on intelligent-video-recording/gst_display.py
> -        # Parse class id from prediction
Document this newPrediction function. Put a comment explaining how is it being used, what is generated by the inferencebin element and when. Remember this demo is intended to show how GstInference works for someone who has never heard about it

2021-03-24 17:13 UTC, bill9889 requested changes

2021-03-24 17:13 UTC, bill9889 commented on intelligent-video-recording/README.md
> +Update the paths to model and labels file on ``config_<type>.cfg`` file.
Check: Update the paths for the model and label files...

2021-03-24 17:13 UTC, bill9889 commented on intelligent-video-recording/README.md
> +In this case, you need to save the labels content into a file named ``coco_labels.txt``.
Check: label contents into a file called...

2021-03-25 18:38 UTC, michaelgruner requested changes

2021-03-25 18:38 UTC, michaelgruner commented on intelligent-video-recording/gst_display.py
> +                print(("Classes_ID and Class_Min_Probability list must be of the same"
Print all errors to stdout.

2021-03-25 18:38 UTC, michaelgruner commented on intelligent-video-recording/gst_display.py
> +                exit(0)
Return a code other than 0 in the case of an error.

2021-03-25 18:38 UTC, michaelgruner commented on intelligent-video-recording/config_detection.cfg
> +OUTPUT_LAYER = 'MobilenetV2/Predictions/Reshape_1'
Please double check if the input and output names are needed in the coral. If not, please leave blank and leave a comment saying this is not needed for the coral, but other backends (such as TensorFlow) may need it.

2021-03-25 18:38 UTC, michaelgruner commented on intelligent-video-recording/gst_display.py
> +                        self.stopRecordingPipeline()
I believe this logic is flawed. The recording will only stop if there is a new prediction. But in the case were a person walks out of the scene and no new predictions are made, the recording will continue forever. We need a timeout mechanism that is restarted with every new valid detection.

2021-03-25 20:48 UTC, michaelgruner approved these changes

2021-03-25 20:48 UTC, michaelgruner commented on intelligent-video-recording/gst_display.py
> +                print(("Classes_ID and Class_Min_Probability list must be of the same"
sorry, I meant stderr

2021-03-25 20:55 UTC, merged